

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: springstudent
    password: springstudent

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
